### ISSUE TITLE
broken json parse

### ISSUE THREAD

**Issue by RichardWright** [clinicjs/node-clinic-heap-profiler#58]
I get the following error:

 Received Ctrl+C, closing process...SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/Wrig83592/.nvm/versions/node/v16.13.1/lib/node_modules/clinic/node_modules/@clinic/heap-profiler/src/analysis/index.js:126:50
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

Node 16.13
latest clinic

**Comment by RichardWright** [comment]
I debugged. The files inside the .clinic folder are empty so the parse fails.

**Comment by RafaelGSS** [comment]
Could you create a reproductible code? The project are you profiling is an HTTP server (don't exit automatically) or a script?

**Comment by RichardWright** [comment]
What do you mean by reproducible code? All I do is run this command:

`clinic heapprofiler -- node dist/index.js`

output:

`[   =] Received Ctrl+C, closing process...INBPUT
.clinic/29687.clinic-heapprofile
raw:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/Wrig83592/.nvm/versions/node/v16.13.1/lib/node_modules/clinic/node_modules/@clinic/heap-profiler/src/analysis/index.js:130:50
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)`

It's a js file, has a graphql server inside it.

**Comment by RafaelGSS** [comment]
It should help https://stackoverflow.com/help/minimal-reproducible-example.

Unfortunately, I can't help without reproducing it locally

**Comment by RafaelGSS** [comment]
Not really. Maybe you can `console.log` before the line that is throwing an error `node_modules/@clinic/heap-profiler/src/analysis/index.js:130:50`

**Comment by RichardWright** [comment]
I can see why it's throwing. the json files are empty. Just trying to work why clinic isn't writing on ctrl c

**Comment by RichardWright** [comment]
The function 'generateHeapSamplingProfile' in ipc.js isn't getting called. That's a difference.

**Comment by RichardWright** [comment]
Is there a document anywhere that will explain the control flow so I can follow it? The spawn part I get lost in

**Comment by RafaelGSS** [comment]
No, it's the source code of the application. `spawn` is a Node.js function to spawn process. 

I'd recommend you provide a minimal reproducible code in case you don't find the possible bug.

**Comment by clok** [comment]
What I have found is that when I use the `heapprofiler` I have to ensure that I press `Crtl + C` to close the process. If I have a script that `process.exit(0)` as the last line, the `heapprofiler` will generate an empty file.

Maybe there is a signal catch in the analysis code that is bypassed by the `process.exit()` call?

**Comment by RafaelGSS** [comment]
> Maybe there is a signal catch in the analysis code that is bypassed by the process.exit() call?

https://github.com/clinicjs/node-clinic-heap-profiler/blob/main/src/injects/ipc.js#L73

**Comment by RichardWright** [comment]
Coming back to this, is this project broken with standard error handling code? Calling process.exit(0) seems to break everything. I've had to advise my colleagues to stop using this tool due to the time sunk into debugging it. A real shame as for a while we actually had something useful to help us.

**Comment by Stono** [comment]
Hello, 
Same problem here.
All our apps implement signal handling for graceful shutdown, for example:

```
const stop = () => {
  exitCount += 1
  if (exitCount === 3) {
    logger.error('exit called multiple times, force quitting')
    process.exit(0)
  }
  setTimeout(function () {
    logger.warn('Shutdown timeout expired, forcefully exiting.')
    process.exit(1)
  }, 10000)
  webServer
    .stop()
    .then(() => {
      return process.exit(0)
    })
    .catch((ex) => {
      logger.error('errors during shutdown', ex)
      process.exit(1)
    })
}
process.on('SIGINT', stop)
process.on('SIGTERM', stop)
```

With this in place, heapprofile doesn't work.

Commenting out the `process.on` lines, and we are all good.
